### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by ghost** [fwestenberg/stookalert#4] opened 2020-03-11 16:06 UTC
delete

**Comment by YRRK** [comment] 2020-03-14 09:47
Maybe the RIVM website was down. I see it now works again. Closing this case.

**Closed as completed by YRRK** 2020-03-14 09:47 UTC

**Comment by fwestenberg** [comment] 2020-03-14 09:55
Thanks for closing. I qasn't able to reproduce this situation. Working fine here. :-)

**Comment by YRRK** [comment] 2020-03-14 17:54
The issue is not always. It comes and goes. 

-- 
YRRK
Furkabaan 677
3524 ZG Utrecht
Tel: 06-20121418
Eml: info@yrrk.nl
KvK: 32098857

> Op 14 mrt. 2020 om 10:56 heeft fwestenberg <notifications@github.com> het volgende geschreven:
> 

﻿
Thanks for closing. I qasn't able to reproduce this situation. Working fine here. :-)
